### ISSUE TITLE
AttributeError: 'TickMonitor' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'?

### ISSUE THREAD

**Issue by KyoMorya** [veighna-global/vnpy_evo#39] opened 2024-03-30 17:10 UTC
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\run.py", line 27, in <module>
    main()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\run.py", line 20, in main
    main_window = MainWindow(main_engine, event_engine)
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\mainwindow.py", line 57, in __init__
    self.init_ui()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\mainwindow.py", line 66, in init_ui
    self.init_widgets()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\mainwindow.py", line 71, in init_widgets
    self.home_widget = HomeWidget(self.main_engine, self.event_engine)
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\mainwindow.py", line 177, in __init__
    self.init_ui()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\mainwindow.py", line 184, in init_ui
    self.tick_monitor = TickMonitor(self.main_engine, self.event_engine)
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\monitor.py", line 228, in __init__
    self.init_ui()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\monitor.py", line 234, in init_ui
    self.init_table()
  File "C:\Users\Administrator\PycharmProjects\vnpybinance\vnpy_evo\trader\ui\monitor.py", line 247, in init_table
    self.setEditTriggers(self.NoEditTriggers)
AttributeError: 'TickMonitor' object has no attribute 'NoEditTriggers'. Did you mean: 'editTriggers'?

TickMonitor checked it and did in fact have no NoEditTriggers attribute and many different errors

**Comment by dancedwolf** [comment] 2024-04-02 01:39
wo have the same Issues ，did you fix it?

**Comment by veighna-global** [comment] 2024-04-04 12:54
This is caused by PySide6 >= 6.3.0 .

Already merged a related PR, so the problem should be solved.

**Closed by veighna-global** 2024-04-04 12:54 UTC
Labels: question

**Comment by linhertz** [comment] 2024-04-22 03:45
I still have this problem

**Comment by veighna-global** [comment] 2024-04-25 01:18
Please use following comnmand to check your PySide6 version?

`pip show PySide6`

And paste the output info here.
